Vagrant.configure("2") do |config| 
 config.vm.box = "ubuntu/focal64" 
 config.vm.provision "shell", inline: <<-SHELL
  sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config 
  systemctl restart sshd.service
  echo "192.168.12.11 nodo10" >> /etc/hosts
 SHELL
 config.vm.define :nodo10 do |ub_config| 
  ub_config.vm.hostname = "nodo10.vm"
  ub_config.vm.network "private_network" , ip:"192.168.12.11" 
  ub_config.vm.provider :virtualbox do |vb|
   vb.name = "nodo10"
   vb.customize ["modifyvm", :id, "--memory", "2048"] 
   vb.customize ["modifyvm", :id, "--cpus", "2"]
  end 
 end
end