# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
 config.vm.box = "ubuntu/focal64"
 config.vm.network "forwarded_port", guest: 22, host: 2522
 config.vm.network "private_network", ip: "192.168.33.10"
 config.vm.provider "virtualbox" do |vb|
 vb.memory = "2048"
 vb.cpus = 4
 end
end