Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provision "shell", inline: <<-SHELL
   sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
   systemctl restart sshd.service
   echo "192.168.12.11 nodo1" >> /etc/hosts
   echo "192.168.12.12 nodo2" >> /etc/hosts
  SHELL

  config.vm.define :nodo1 do |ub_config|
    ub_config.vm.hostname = "nodo1.vm"
    ub_config.vm.network "private_network" , ip:"192.168.12.11"
    ub_config.vm.provider :virtualbox do |vb|
      vb.name = "nodo1"
      vb.customize ["modifyvm", :id, "--memory", "768"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end

  config.vm.define :nodo2 do |ub_config|
    ub_config.vm.hostname = "nodo2.vm"
    ub_config.vm.network "private_network" , ip:"192.168.12.12"
    ub_config.vm.provider :virtualbox do |vb|
      vb.name = "nodo2"
      vb.customize ["modifyvm", :id, "--memory", "768"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
    end
  end
end
